global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'task-manager'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:8000']  # Важно: имя сервиса из docker-compose
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']